"""
books/lolo-hero/config.py — Book data manifest

Generated by KDP Dashboard.
Identity, CHARACTERS, and PAGE_SEQUENCE are managed via the dashboard.
Edit TITLE_PAGE_LINES, COPYRIGHT_PAGE_LINES, BACK_PAGE_LINES directly if needed.
"""

import pathlib

# ── Identity ───────────────────────────────────────────────────────────────────

CATEGORY       = "story"
PUBLISHED      = False
STORY_FORMAT   = "colored"
STORY_LAYOUT   = "top_bottom"
LANGUAGES      = ["fr"]
TITLE          = "lolo hero"
SUBTITLE       = ""
AUTHOR         = ""
INTRO_TEXT     = ""
VALUES_LEARNED = ""

# ── Paths ──────────────────────────────────────────────────────────────────────

IMAGES_DIR = pathlib.Path(__file__).parent.parent.parent / "images" / "lolo-hero"
TESTPEN    = "lolo-hero_testpen.png"

# ── Story settings ────────────────────────────────────────────────────────────

STORY_BASE_PROMPT = "soft watercolor children's book illustration, warm palette, gentle lighting"

# ── Story Pages ───────────────────────────────────────────────────────────────

PAGES = [
    {
        "page_number":  1,
        "text":         {"fr": "Little said woke up with a big stretch, right at the edge of the whispering enchanted forest. Sunlight dappled through the leaves, painting the ground in shimmering gold. \"Today,\" thought said, \"is the day for a grand adventure!\" The air was fresh and filled with the promise of discovery.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "A small child named 'said' waking up with a big stretch at the very edge of a magical, sun-dappled enchanted forest. Sunlight streaming through leaves."
    },
    {
        "page_number":  2,
        "text":         {"fr": "The enchanted forest called to said with its mysterious sounds and hidden paths. Every rustle of a bush, every chirp of a bird, made said's heart beat with excitement. said took a deep breath, clutching a small, worn backpack, ready to step deeper into the unknown.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "A small child named 'said' standing at the entrance of a vibrant enchanted forest, looking curious and excited, holding a small backpack. Forest path ahead."
    },
    {
        "page_number":  3,
        "text":         {"fr": "Not far into the woods, said heard a soft whimpering. Peeking around a mossy tree, said saw a tiny, fluffy dog tangled in a thorny vine. Carefully, said approached and gently freed the little creature. The dog wagged its tail happily, nudging said's hand.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "A small child named 'said' gently freeing a tiny, fluffy dog from a thorny vine in a magical enchanted forest. The dog looks grateful."
    },
    {
        "page_number":  4,
        "text":         {"fr": "From that moment on, the little dog, who said decided to call 'Wags', became a loyal friend. They explored together, sharing berries and laughter. Wags trotted faithfully by said's side, always ready for the next discovery, making said feel much braver.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "The small child 'said' and the fluffy dog 'Wags' exploring together in the enchanted forest, sharing berries and laughing. The dog is trotting happily beside the child."
    },
    {
        "page_number":  5,
        "text":         {"fr": "Their adventure led them to a winding path that ended at a very old, wobbly bridge over a deep, dark gorge. A sign warned, \"Only those who understand the ancient ways may cross.\" said felt a little scared, looking down at the swirling mist below. How could they get to the other side?", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "A small child named 'said' and the dog 'Wags' standing before a very old, wobbly wooden bridge over a deep, dark gorge. Mist swirls below. A mysterious sign is visible. The child looks a little scared."
    },
    {
        "page_number":  6,
        "text":         {"fr": "\"This looks too dangerous, Wags,\" whispered said, clutching Wags close. \"What if the bridge breaks? What if we fall?\" said's knees felt like jelly. They desperately wanted to continue their journey, but this challenge seemed too big, too scary.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "Close-up on the child 'said' looking very worried and scared, clutching the dog 'Wags' tightly, at the edge of the wobbly bridge. The gorge and mist are in the background."
    },
    {
        "page_number":  7,
        "text":         {"fr": "Just then, an ancient, wise-looking owl landed nearby. \"To cross,\" hooted the owl, \"you must demonstrate respect old people.\" said thought hard. \"Aha!\" said exclaimed, remembering stories. said carefully inspected the bridge, then slowly and respectfully stepped onto it, trusting its old strength, just as one would trust wisdom.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "A wise-looking ancient owl perched on a branch near 'said' and 'Wags'. 'said' is thinking hard, then begins to carefully and respectfully step onto the old bridge, with a determined expression."
    },
    {
        "page_number":  8,
        "text":         {"fr": "With each careful step, said remembered the owl's words and the power of respect old people. The bridge, though old, held firm. On the other side, said felt a warmth spread through said's heart, knowing that being brave meant more than just not being scared; it meant understanding and showing respect old people. Wags wagged happily, proud of said.", "ar": "", "en": "", "es": ""},
        "moral":        "",
        "image_prompt": "The child 'said' and the dog 'Wags' standing safely on the other side of the ancient bridge, looking happy and relieved. The child has a knowing, thoughtful smile, reflecting the lesson learned. The magical forest continues beyond."
    }
]

# ── Character roster ──────────────────────────────────────────────────────────

CHARACTERS = []

# ── Page sequence ─────────────────────────────────────────────────────────────

PAGE_SEQUENCE = [
    ("lolo-hero_page_1.png", "Page 1"),
    ("lolo-hero_page_2.png", "Page 2"),
    ("lolo-hero_page_3.png", "Page 3"),
    ("lolo-hero_page_4.png", "Page 4"),
    ("lolo-hero_page_5.png", "Page 5"),
    ("lolo-hero_page_6.png", "Page 6"),
    ("lolo-hero_page_7.png", "Page 7"),
    ("lolo-hero_page_8.png", "Page 8")
]

# ── KDP Metadata ────────────────────────────────────────────────────────────────

KDP_METADATA = {}

# ── Title-page layout ─────────────────────────────────────────────────────────

TITLE_PAGE_LINES = (('lolo hero', 120, True, (0, 0, 0)),
 ('Coloring Our Stories', 72, True, (0, 0, 0)),
 ('', 36, False, (255, 255, 255)),
 ('', 46, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)))

# ── Copyright-page layout ────────────────────────────────────────────────────

COPYRIGHT_PAGE_LINES = (('© 2026 All rights reserved.', 32, True, (40, 40, 40)),
 ('', 18, False, (255, 255, 255)),
 ('No part of this publication may be reproduced', 26, False, (80, 80, 80)),
 ('or distributed without prior written permission.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('All characters are original fictional archetypes', 26, False, (80, 80, 80)),
 ('inspired by the world of anime.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('Printed in the United States of America', 26, False, (80, 80, 80)),
 ('First Edition', 26, False, (80, 80, 80)))

# ── Back-matter layout ───────────────────────────────────────────────────────

BACK_PAGE_LINES = (('Thank you for coloring with us!', 55, True, (0, 0, 0)),
 ('', 30, False, (255, 255, 255)),
 ('If you enjoyed this book,', 40, False, (60, 60, 60)),
 ('please leave a review on Amazon.', 40, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('It means the world to us', 34, False, (110, 110, 110)),
 ('and helps other families discover it.', 34, False, (110, 110, 110)))
