"""
books/joudia-s-world/config.py — Book data manifest

Generated by KDP Dashboard.
Identity, CHARACTERS, and PAGE_SEQUENCE are managed via the dashboard.
Edit TITLE_PAGE_LINES, COPYRIGHT_PAGE_LINES, BACK_PAGE_LINES directly if needed.
"""

import pathlib

# ── Identity ───────────────────────────────────────────────────────────────────

CATEGORY       = "story"
STORY_FORMAT   = "colored"
STORY_LAYOUT   = "top_bottom"
LANGUAGES      = ["fr"]
TITLE          = "Joudia's world"
SUBTITLE       = ""
AUTHOR         = ""
INTRO_TEXT     = ""
VALUES_LEARNED = ""

# ── Paths ──────────────────────────────────────────────────────────────────────

IMAGES_DIR = pathlib.Path(__file__).parent.parent.parent / "images" / "joudia-s-world"
TESTPEN    = "joudia-s-world_testpen.png"

# ── Story settings ────────────────────────────────────────────────────────────

STORY_BASE_PROMPT = "soft watercolor children's book illustration, warm palette, gentle lighting"

# ── Story Pages ───────────────────────────────────────────────────────────────

PAGES = [
    {
        "page_number":  1,
        "text":         {"fr": "Joudia woke up at the edge of the enchanted forest, ready for a big adventure.", "ar": "استيقظت جوديا على حافة الغابة المسحورة، مستعدة لمغامرة كبيرة.", "en": "Joudia woke up at the edge of the enchanted forest, ready for a big adventure.", "es": "Joudia se despertó en el borde del bosque encantado, lista para una gran aventura."},
        "moral":        "",
        "image_prompt": "Young girl, dark brown curly hair often in pigtails or a high bun, dark brown eyes, warm olive skin, cheerful smile. standing at the edge of a enchanted forest, soft morning light, curious expression"
    },
    {
        "page_number":  2,
        "text":         {"fr": "Along the way, Joudia met a friendly koala who became a loyal friend.", "ar": "", "en": "Along the way, Joudia met a friendly koala who became a loyal friend.", "es": ""},
        "moral":        "",
        "image_prompt": "Young girl, dark brown curly hair often in pigtails or a high bun, dark brown eyes, warm olive skin, cheerful smile. meeting a friendly koala in the enchanted forest, warm and joyful"
    },
    {
        "page_number":  3,
        "text":         {"fr": "Together they faced a tricky problem, and Joudia felt a little scared.", "ar": "", "en": "Together they faced a tricky problem, and Joudia felt a little scared.", "es": ""},
        "moral":        "",
        "image_prompt": "Young girl, dark brown curly hair often in pigtails or a high bun, dark brown eyes, warm olive skin, cheerful smile. and a koala facing a challenge in the enchanted forest, dramatic but gentle"
    },
    {
        "page_number":  4,
        "text":         {"fr": "By being brave, Joudia learned the power of parent's repect.", "ar": "", "en": "By being brave, Joudia learned the power of parent's repect.", "es": ""},
        "moral":        "",
        "image_prompt": "Young girl, dark brown curly hair often in pigtails or a high bun, dark brown eyes, warm olive skin, cheerful smile. smiling proudly in the enchanted forest with a koala, triumphant glow"
    }
]

# ── Character roster ──────────────────────────────────────────────────────────

CHARACTERS = []

# ── Page sequence ─────────────────────────────────────────────────────────────

PAGE_SEQUENCE = [
    ("joudia-s-world_page_1.png", "Page 1"),
    ("joudia-s-world_page_2.png", "Page 2"),
    ("joudia-s-world_page_3.png", "Page 3"),
    ("joudia-s-world_page_4.png", "Page 4")
]

# ── KDP Metadata ────────────────────────────────────────────────────────────────

KDP_METADATA = {}

# ── Title-page layout ─────────────────────────────────────────────────────────

TITLE_PAGE_LINES = (("Joudia's world", 120, True, (0, 0, 0)),
 ('Coloring Our Stories', 72, True, (0, 0, 0)),
 ('', 36, False, (255, 255, 255)),
 ('', 46, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)))

# ── Copyright-page layout ────────────────────────────────────────────────────

COPYRIGHT_PAGE_LINES = (('© 2026 All rights reserved.', 32, True, (40, 40, 40)),
 ('', 18, False, (255, 255, 255)),
 ('No part of this publication may be reproduced', 26, False, (80, 80, 80)),
 ('or distributed without prior written permission.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('All characters are original fictional archetypes', 26, False, (80, 80, 80)),
 ('inspired by the world of anime.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('Printed in the United States of America', 26, False, (80, 80, 80)),
 ('First Edition', 26, False, (80, 80, 80)))

# ── Back-matter layout ───────────────────────────────────────────────────────

BACK_PAGE_LINES = (('Thank you for coloring with us!', 55, True, (0, 0, 0)),
 ('', 30, False, (255, 255, 255)),
 ('If you enjoyed this book,', 40, False, (60, 60, 60)),
 ('please leave a review on Amazon.', 40, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('It means the world to us', 34, False, (110, 110, 110)),
 ('and helps other families discover it.', 34, False, (110, 110, 110)))
