"""
books/coiffeur-roi/config.py — Book data manifest

Generated by KDP Dashboard.
Identity, CHARACTERS, and PAGE_SEQUENCE are managed via the dashboard.
Edit TITLE_PAGE_LINES, COPYRIGHT_PAGE_LINES, BACK_PAGE_LINES directly if needed.
"""

import pathlib

# ── Identity ───────────────────────────────────────────────────────────────────

CATEGORY       = "story"
PUBLISHED      = True
TEMPLATE_SLUG       = "coiffeur-roi"
PIPELINE_STAGE      = "published"
DEFAULT_CHARACTER_DESC = "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression."
STORY_FORMAT   = "colored"
STORY_LAYOUT   = "top_bottom"
LANGUAGES      = ["fr"]
TITLE          = "Le Petit Coiffeur, la Flûte et le Secret du Roi"
SUBTITLE       = ""
AUTHOR         = ""
INTRO_TEXT     = "Il était une fois un roi orgueilleux et un jeune garçon courageux qui, grâce à sa gentillesse et son intelligence, a su déjouer les pièges et trouver le chemin du retour."
VALUES_LEARNED = "Courage, gentillesse, ruse, partage, amitié, et l'importance de ne pas juger les autres sur leur apparence."

# ── Paths ──────────────────────────────────────────────────────────────────────

IMAGES_DIR = pathlib.Path(__file__).parent.parent.parent / "images" / "coiffeur-roi"
TESTPEN    = "coiffeur-roi_testpen.png"

# ── Story settings ────────────────────────────────────────────────────────────

STORY_BASE_PROMPT = "A whimsical children's storybook, vibrant and warm color palette, soft lighting, enchanting atmosphere, detailed illustrations with a touch of magic."

# ── Story Pages ───────────────────────────────────────────────────────────────

PAGES = [
    {
        "page_number":  1,
        "text":         {"fr": "Il était une fois un roi très orgueilleux qui cachait un grand secret sous sa couronne : il avait une corne qui poussait sur sa tête. Pour que personne ne découvre son secret, le roi faisait disparaître tous les coiffeurs qui venaient au château. Un jour, ce fut le tour d'un jeune et gentil garçon. Avant son départ, sa maman, qui l'aimait très fort, lui prépara trois délicieux gâteaux pour son voyage.", "en": "Once upon a time, there was a very proud king who hid a big secret under his crown: he had a horn growing on his head. So that no one would discover his secret, the king made all the barbers who came to the castle disappear. One day, it was the turn of a young and kind boy. Before he left, his mother, who loved him very much, prepared three delicious cakes for his journey.", "es": "Érase una vez un rey muy orgulloso que escondía un gran secreto bajo su corona: tenía un cuerno que le crecía en la cabeza. Para que nadie descubriera su secreto, el rey hacía desaparecer a todos los barberos que venían al castillo. Un día, le tocó el turno a un joven y amable muchacho. Antes de su partida, su mamá, que lo quería mucho, le preparó tres deliciosos pasteles para su viaje.", "ar": "كان هناك ملك متكبر جدًا يخفي سرًا كبيرًا تحت تاجه: كان لديه قرن ينمو على رأسه. لكي لا يكتشف أحد سره، كان الملك يتخلص من جميع الحلاقين الذين يأتون إلى القلعة. في يوم من الأيام، جاء دور فتى شاب ولطيف. قبل مغادرته، أعدت له والدته، التي كانت تحبه كثيرًا، ثلاثة كعكات لذيذة لرحلته."},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. receiving three delicious cakes from his loving mother, with a grand, imposing castle visible in the background under a bright sky."
    },
    {
        "page_number":  2,
        "text":         {"fr": "Arrivé au château, le petit garçon commença à couper les cheveux du roi. Quand le roi enleva son chapeau, le garçon vit la corne ! Il fut très surpris mais resta très calme et fit semblant de ne rien voir pour se protéger. À la fin, le roi lui dit de prendre des pièces d'or dans un grand coffre en récompense. Mais attention, c'était un piège ! Le roi le poussa, et le garçon tomba tout au fond du coffre, dans une grotte sombre.", "en": "Upon arriving at the castle, the little boy began to cut the king's hair. When the king removed his hat, the boy saw the horn! He was very surprised but remained very calm and pretended not to see anything to protect himself. In the end, the king told him to take gold coins from a large chest as a reward. But beware, it was a trap! The king pushed him, and the boy fell to the very bottom of the chest, into a dark cave.", "es": "Al llegar al castillo, el pequeño muchacho comenzó a cortar el cabello del rey. Cuando el rey se quitó el sombrero, ¡el muchacho vio el cuerno! Se sorprendió mucho pero se mantuvo muy tranquilo y fingió no ver nada para protegerse. Al final, el rey le dijo que tomara monedas de oro de un gran cofre como recompensa. ¡Pero cuidado, era una trampa! El rey lo empujó, y el muchacho cayó al fondo del cofre, en una cueva oscura.", "ar": "عند وصوله إلى القلعة، بدأ الصبي الصغير بقص شعر الملك. عندما خلع الملك قبعته، رأى الصبي القرن! تفاجأ كثيراً لكنه ظل هادئاً جداً وتظاهر بأنه لم ير شيئاً ليحمي نفسه. في النهاية، طلب منه الملك أن يأخذ قطعاً ذهبية من صندوق كبير كمكافأة. لكن حذار، كان فخاً! دفعه الملك، وسقط الصبي في قاع الصندوق، في كهف مظلم."},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. falling into a deep, dark chest, with the silhouette of the king looking down from above, a single ray of light illuminating the falling boy."
    },
    {
        "page_number":  3,
        "text":         {"fr": "Dans la grotte obscure, le garçon rencontra un énorme serpent. Au lieu d'avoir peur, il sortit sa petite flûte de bois (un nây) et se mit à jouer. La jolie musique fit danser le serpent de joie ! Le garçon lui offrit alors son premier gâteau. Pour le remercier de ce gentil cadeau, le serpent l'aida à trouver la sortie de la grotte.", "en": "In the dark cave, the boy met an enormous snake. Instead of being afraid, he took out his small wooden flute (a nay) and began to play. The beautiful music made the snake dance with joy! The boy then offered him his first cake. To thank him for this kind gift, the snake helped him find the exit from the cave.", "es": "En la oscura cueva, el muchacho se encontró con una enorme serpiente. En lugar de tener miedo, sacó su pequeña flauta de madera (un nay) y empezó a tocar. ¡La hermosa música hizo bailar a la serpiente de alegría! El muchacho le ofreció entonces su primer pastel. Para agradecerle este amable regalo, la serpiente lo ayudó a encontrar la salida de la cueva.", "ar": "في الكهف المظلم، التقى الصبي بثعبان ضخم. بدلاً من أن يخاف، أخرج نايَه الخشبي الصغير وبدأ يعزف. جعلت الموسيقى الجميلة الثعبان يرقص فرحاً! ثم قدم له الصبي كعكته الأولى. لشكره على هذه الهدية اللطيفة، ساعده الثعبان في العثور على مخرج الكهف."},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. playing a small wooden flute for a large, friendly-looking snake, who is dancing joyfully in a dimly lit cave, with A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. offering a cake."
    },
    {
        "page_number":  4,
        "text":         {"fr": "En sortant, le garçon se retrouva dans une grande forêt et tomba nez à nez avec un loup au ventre qui gargouillait de faim. Le garçon grimpa vite dans un arbre, mais finit par tomber. Heureusement, il sortit son deuxième gâteau et l'offrit au loup. Le loup, ravi d'avoir le ventre plein, devint son ami et le prit sur son dos pour le sortir de la forêt.", "en": "Upon exiting, the boy found himself in a large forest and came face to face with a wolf whose stomach was growling with hunger. The boy quickly climbed a tree, but eventually fell. Fortunately, he took out his second cake and offered it to the wolf. The wolf, delighted to have a full belly, became his friend and carried him on his back to get him out of the forest.", "es": "Al salir, el muchacho se encontró en un gran bosque y se topó con un lobo cuyo estómago gruñía de hambre. El muchacho trepó rápidamente a un árbol, pero finalmente se cayó. Afortunadamente, sacó su segundo pastel y se lo ofreció al lobo. El lobo, encantado de tener el estómago lleno, se hizo su amigo y lo llevó sobre su espalda para sacarlo del bosque.", "ar": "عند الخروج، وجد الصبي نفسه في غابة كبيرة وواجه ذئباً بطنه يقرقع من الجوع. صعد الصبي بسرعة إلى شجرة، لكنه سقط في النهاية. لحسن الحظ، أخرج كعكته الثانية وقدمها للذئب. الذئب، سعيداً بامتلاء بطنه، أصبح صديقه وحمله على ظهره ليخرجه من الغابة."},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. riding on the back of a large, friendly wolf through a vibrant, sun-dappled forest, looking happy and adventurous."
    },
    {
        "page_number":  5,
        "text":         {"fr": "Le garçon arriva près d'une petite cabane au bord d'un lac, où vivait une sorcière qui voulait l'enfermer. Le petit garçon lui demanda la permission de jouer de sa flûte une dernière fois. La musique apaisa la sorcière. Il lui donna son tout dernier gâteau et lui raconta son aventure. La sorcière, touchée, devint gentille et lui offrit un vieux manteau magique : s'il le mettait à l'envers, il se transformait en vieux monsieur avec une barbe blanche !", "en": "The boy arrived near a small hut by a lake, where a witch lived who wanted to trap him. The little boy asked her permission to play his flute one last time. The music soothed the witch. He gave her his very last cake and told her his adventure. The witch, touched, became kind and offered him an old magic cloak: if he put it on inside out, he would transform into an old man with a white beard!", "es": "El muchacho llegó cerca de una pequeña cabaña a orillas de un lago, donde vivía una bruja que quería encerrarlo. El pequeño muchacho le pidió permiso para tocar su flauta una última vez. La música apaciguó a la bruja. Le dio su último pastel y le contó su aventura. La bruja, conmovida, se volvió amable y le ofreció un viejo manto mágico: si se lo ponía al revés, ¡se transformaría en un anciano con barba blanca!", "ar": "وصل الصبي بالقرب من كوخ صغير على ضفة بحيرة، حيث كانت تعيش ساحرة أرادت حبسه. طلب الصبي الصغير منها الإذن بالعزف على نايَه لآخر مرة. هدأت الموسيقى الساحرة. أعطاها آخر كعكة له وحكى لها مغامرته. الساحرة، متأثرة، أصبحت لطيفة وقدمت له معطفاً سحرياً قديماً: إذا ارتداه مقلوباً، يتحول إلى رجل عجوز بلحية بيضاء!"},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. offering his last cake to a kind-looking witch by a serene lake, receiving a shimmering magical cloak, with a small hut in the background."
    },
    {
        "page_number":  6,
        "text":         {"fr": "Le petit garçon eut une idée géniale. Il mit son manteau magique, se transforma en vieil homme aux cheveux blancs, et retourna au château. Devant les gardes, il dit : \"Je viens pour coiffer le roi !\" et on le laissa entrer. Sans être reconnu, il coupa de nouveau les cheveux du roi.", "en": "The little boy had a brilliant idea. He put on his magic cloak, transformed into an old man with white hair, and returned to the castle. In front of the guards, he said: \"I've come to cut the king's hair!\" and they let him in. Without being recognized, he cut the king's hair again.", "es": "El pequeño muchacho tuvo una idea genial. Se puso su manto mágico, se transformó en un anciano de cabellos blancos y regresó al castillo. Delante de los guardias, dijo: \"¡Vengo a cortar el cabello del rey!\" y lo dejaron entrar. Sin ser reconocido, volvió a cortar el cabello del rey.", "ar": "جاءت الصبي الصغير فكرة رائعة. ارتدى معطفه السحري، وتحول إلى رجل عجوز ذي شعر أبيض، وعاد إلى القلعة. أمام الحراس، قال: \"جئت لأقص شعر الملك!\" وسمحوا له بالدخول. دون أن يتعرف عليه أحد، قص شعر الملك مرة أخرى."},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. disguised as a wise old man with a long white beard, confidently walking through the grand gates of the castle, past surprised guards."
    },
    {
        "page_number":  7,
        "text":         {"fr": "Comme la première fois, le roi lui dit d'aller prendre de l'or dans le coffre. Mais le garçon était malin. Il cria : \"Oh là là ! Je n'ai jamais vu autant d'or de toute ma vie !\" Le roi, très curieux, se pencha pour regarder dans le coffre. Hop ! Le garçon le poussa dedans !", "en": "Just like the first time, the king told him to go take gold from the chest. But the boy was clever. He cried out: \"Oh my! I've never seen so much gold in all my life!\" The king, very curious, leaned in to look into the chest. Whoosh! The boy pushed him in!", "es": "Como la primera vez, el rey le dijo que fuera a tomar oro del cofre. Pero el muchacho era astuto. Gritó: \"¡Oh, la la! ¡Nunca he visto tanto oro en toda mi vida!\" El rey, muy curioso, se inclinó para mirar dentro del cofre. ¡Hop! ¡El muchacho lo empujó dentro!", "ar": "كما في المرة الأولى، طلب منه الملك أن يذهب ليأخذ الذهب من الصندوق. لكن الصبي كان ذكياً. صرخ: \"يا إلهي! لم أرَ كل هذا الذهب في حياتي كلها!\" الملك، فضولي جداً، انحنى لينظر في الصندوق. وفجأة! دفعه الصبي إلى الداخل!"},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. disguised as an old man, cleverly pushing the curious king, who is leaning over, into the deep, dark gold chest, with a mischievous grin."
    },
    {
        "page_number":  8,
        "text":         {"fr": "Le garçon enleva vite son manteau magique, redevint un petit enfant et s'échappa du château sans que personne ne le voie. Pendant que le vilain roi se retrouvait coincé dans la grotte avec le grand serpent, le petit garçon courut jusque chez lui pour retrouver sa maman. Ils vécurent heureux, et plus jamais personne n'entendit parler du roi à la corne !", "en": "The boy quickly took off his magic cloak, became a little child again, and escaped from the castle without anyone seeing him. While the wicked king found himself stuck in the cave with the big snake, the little boy ran all the way home to find his mother. They lived happily ever after, and no one ever heard of the king with the horn again!", "es": "El muchacho se quitó rápidamente su manto mágico, volvió a ser un niño pequeño y escapó del castillo sin que nadie lo viera. Mientras el malvado rey se encontraba atrapado en la cueva con la gran serpiente, el pequeño muchacho corrió hasta su casa para reencontrarse con su mamá. Vivieron felices, ¡y nunca más se volvió a saber del rey con el cuerno!", "ar": "خلع الصبي معطفه السحري بسرعة، وعاد طفلاً صغيراً وهرب من القلعة دون أن يراه أحد. بينما كان الملك الشرير عالقاً في الكهف مع الثعبان الكبير، ركض الصبي الصغير إلى منزله ليلتقي بوالدته. عاشوا بسعادة، ولم يسمع أحد عن الملك ذي القرن بعد ذلك أبداً!"},
        "moral":        "",
        "image_prompt": "A young boy with bright, curious brown eyes, short messy brown hair, wearing a simple blue tunic and brown trousers, with a kind and determined expression. running joyfully through a vibrant, sunlit path towards a cozy, welcoming house, with his loving mother waiting at the door, leaving the distant castle behind."
    }
]

# ── Character roster ──────────────────────────────────────────────────────────

CHARACTERS = []

# ── Page sequence ─────────────────────────────────────────────────────────────

PAGE_SEQUENCE = [
    ("coiffeur-roi_page_1.png", "Page 1"),
    ("coiffeur-roi_page_2.png", "Page 2"),
    ("coiffeur-roi_page_3.png", "Page 3"),
    ("coiffeur-roi_page_4.png", "Page 4"),
    ("coiffeur-roi_page_5.png", "Page 5"),
    ("coiffeur-roi_page_6.png", "Page 6"),
    ("coiffeur-roi_page_7.png", "Page 7"),
    ("coiffeur-roi_page_8.png", "Page 8")
]

# ── KDP Metadata ────────────────────────────────────────────────────────────────

KDP_METADATA = {}

# ── Title-page layout ─────────────────────────────────────────────────────────

TITLE_PAGE_LINES = (('Le Petit Coiffeur, la Flûte et le Secret du Roi', 120, True, (0, 0, 0)),
 ('Coloring Our Stories', 72, True, (0, 0, 0)),
 ('', 36, False, (255, 255, 255)),
 ('', 46, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)))

# ── Copyright-page layout ────────────────────────────────────────────────────

COPYRIGHT_PAGE_LINES = (('© 2026 All rights reserved.', 32, True, (40, 40, 40)),
 ('', 18, False, (255, 255, 255)),
 ('No part of this publication may be reproduced', 26, False, (80, 80, 80)),
 ('or distributed without prior written permission.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('All characters are original fictional archetypes', 26, False, (80, 80, 80)),
 ('inspired by the world of anime.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('Printed in the United States of America', 26, False, (80, 80, 80)),
 ('First Edition', 26, False, (80, 80, 80)))

# ── Back-matter layout ───────────────────────────────────────────────────────

BACK_PAGE_LINES = (('Thank you for coloring with us!', 55, True, (0, 0, 0)),
 ('', 30, False, (255, 255, 255)),
 ('If you enjoyed this book,', 40, False, (60, 60, 60)),
 ('please leave a review on Amazon.', 40, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('It means the world to us', 34, False, (110, 110, 110)),
 ('and helps other families discover it.', 34, False, (110, 110, 110)))
