"""
books/book1-90s-legends/config.py — Book data manifest

Generated by KDP Dashboard.
Identity, CHARACTERS, and PAGE_SEQUENCE are managed via the dashboard.
Edit TITLE_PAGE_LINES, COPYRIGHT_PAGE_LINES, BACK_PAGE_LINES directly if needed.
"""

import pathlib

# ── Identity ───────────────────────────────────────────────────────────────────

CATEGORY       = "coloring"
STORY_FORMAT   = "colored"
STORY_LAYOUT   = "top_bottom"
LANGUAGES      = ["fr"]
TITLE          = "90s Legends: Coloring Our Stories"
SUBTITLE       = "A Timeless Quest — Anime Coloring Book for Dads & Kids"
AUTHOR         = "Marco Belghiti"
INTRO_TEXT     = ""
VALUES_LEARNED = ""

# ── Paths ──────────────────────────────────────────────────────────────────────

IMAGES_DIR = pathlib.Path(__file__).parent.parent.parent / "images" / "book1-90s"
TESTPEN    = "book1_testpen.png"

# ── Story settings ────────────────────────────────────────────────────────────

STORY_BASE_PROMPT = ""

# ── Story Pages ───────────────────────────────────────────────────────────────

PAGES = []

# ── Character roster ──────────────────────────────────────────────────────────

CHARACTERS = [
    {
        "id":     "conan",
        "name":   "The Little Detective",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "slam1_portrait",
        "name":   "The Basketball Genius",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "soccer-legend_portrait",
        "name":   "The Soccer Legend",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "dragonball-superwarrior",
        "name":   "The Super Warrior",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe1",
        "name":   "Scene — The Gang",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "naruto",
        "name":   "The Hidden Leaf Ninja",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "vegeta_portrait",
        "name":   "The Prince of Warriors",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "dark-avenger_portrait",
        "name":   "The Dark Avenger",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe7-grid",
        "name":   "All Heroes — Overview",
        "series": "",
        "prompt": "Adult coloring book page, line art only, absolutely zero fills anywhere. Character: groupe7-grid. Full body, centered, pure white background. Draw ONLY black outlines — every single area inside the outlines must remain pure white and empty for coloring. CRITICAL rules that must never be broken: (1) hair must be drawn as individual strands or line details — NEVER filled solid or gray, (2) boots, shoes and dark clothing must be outlined shapes with interior details — NEVER filled, (3) zero black fills, zero gray fills, zero shading, zero gradients anywhere on the image. Style reference: Johanna Basford coloring book — bold clean outlines, all interior areas white. 300 DPI, high contrast line art, ready to color.",
    },
    {
        "id":     "digimon",
        "name":   "The Digimon Tamer",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "blade_clean_portrait",
        "name":   "The Blade Spinner",
        "series": "",
        "prompt": "Adult coloring book page, line art only, absolutely zero fills anywhere. Character: blade_clean_portrait from Be blade. Full body, centered, pure white background. Draw ONLY black outlines — every single area inside the outlines must remain pure white and empty for coloring. CRITICAL rules that must never be broken: (1) hair must be drawn as individual strands or line details — NEVER filled solid or gray, (2) boots, shoes and dark clothing must be outlined shapes with interior details — NEVER filled, (3) zero black fills, zero gray fills, zero shading, zero gradients anywhere on the image. Style reference: Johanna Basford coloring book — bold clean outlines, all interior areas white. 300 DPI, high contrast line art, ready to color.",
    },
    {
        "id":     "hunter_clean_portrait",
        "name":   "The Hunter Kid",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe2",
        "name":   "Scene — Adventure",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "prince_warrior",
        "name":   "The Prince of Warriors",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "samurai-foul_portrait",
        "name":   "The Silver Samurai Fool",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe3",
        "name":   "Scene — Warriors Unite",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "Alchemist",
        "name":   "The Alchemist Brother",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "deathnote_portrait",
        "name":   "The Death Strategist",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "soul-reaper_clean",
        "name":   "The Soul Reaper",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe5",
        "name":   "Scene — Legends",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "demon-buttler",
        "name":   "The Demon Butler",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe4",
        "name":   "Scene — Rivals",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "yugioh_portrait",
        "name":   "The Card Master",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "chin_portrait",
        "name":   "The Wandering Swordsman",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe8-grid",
        "name":   "All Heroes — Grid",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "remi",
        "name":   "The Young Traveler",
        "series": "",
        "prompt": "",
    },
    {
        "id":     "groupe6",
        "name":   "Scene — Final Battle",
        "series": "",
        "prompt": "",
    }
]

# ── Page sequence ─────────────────────────────────────────────────────────────

PAGE_SEQUENCE = [
    ("book1_conan.png", "The Little Detective"),
    ("book1_slam1_portrait.png", "The Basketball Genius"),
    ("book1_soccer-legend_portrait.png", "The Soccer Legend"),
    ("book1_dragonball-superwarrior.png", "The Super Warrior"),
    ("book1_groupe1.png", "Scene — The Gang"),
    ("book1_naruto.png", "The Hidden Leaf Ninja"),
    ("book1_vegeta_portrait.png", "The Prince of Warriors"),
    ("book1_dark-avenger_portrait.png", "The Dark Avenger"),
    ("book1_groupe7-grid.png", "All Heroes — Overview"),
    ("book1_digimon.png", "The Digimon Tamer"),
    ("book1_blade_clean_portrait.png", "The Blade Spinner"),
    ("book1_hunter_clean_portrait.png", "The Hunter Kid"),
    ("book1_groupe2.png", "Scene — Adventure"),
    ("book1_prince_warrior.png", "The Prince of Warriors"),
    ("book1_samurai-foul_portrait.png", "The Silver Samurai Fool"),
    ("book1_groupe3.png", "Scene — Warriors Unite"),
    ("book1_Alchemist.png", "The Alchemist Brother"),
    ("book1_deathnote_portrait.png", "The Death Strategist"),
    ("book1_soul-reaper_clean.png", "The Soul Reaper"),
    ("book1_groupe5.png", "Scene — Legends"),
    ("book1_demon-buttler.png", "The Demon Butler"),
    ("book1_groupe4.png", "Scene — Rivals"),
    ("book1_yugioh_portrait.png", "The Card Master"),
    ("book1_chin_portrait.png", "The Wandering Swordsman"),
    ("book1_groupe8-grid.png", "All Heroes — Grid"),
    ("book1_remi.png", "The Young Traveler"),
    ("book1_groupe6.png", "Scene — Final Battle")
]

# ── KDP Metadata ────────────────────────────────────────────────────────────────

KDP_METADATA = {
    "description": "Remember Saturday morning cartoons? The heroes that shaped your childhood are back — this time on the page for you to color together.\n\n90s Legends is a coloring book built for two generations: dads who grew up with these classics and kids discovering them for the first time. 27 pages of clean, bold line art featuring iconic 90s anime archetypes — the little detective, the super warrior, the hidden leaf ninja, the soul reaper, and more.\n\n• 27 full-page coloring pages (8.5\" × 11\")\n• Original fictional archetypes inspired by 90s anime classics\n• Bold, clean line art — perfect for markers, colored pencils, or crayons\n• Includes group scene spreads for maximum color adventure\n• Blank back pages — no bleed-through\n\nPerfect for anime dads who never stopped watching, and the perfect weekend activity to share with your kids.",
    "keywords": [
        "anime coloring book for adults",
        "90s anime coloring book",
        "anime coloring book kids",
        "dad and kids activity book",
        "coloring book for men",
        "anime activity book family",
        "dragon ball coloring book"
    ],
    "categories": [
        "JUVENILE NONFICTION / Activity Books / Coloring",
        "GAMES & ACTIVITIES / Coloring Books"
    ],
    "price_usd": 8.99,
    "amazon_asin": ""
}

# ── Title-page layout ─────────────────────────────────────────────────────────

TITLE_PAGE_LINES = (('90s Legends', 120, True, (0, 0, 0)),
 ('Coloring Our Stories', 72, True, (0, 0, 0)),
 ('', 36, False, (255, 255, 255)),
 ('A coloring book for dads who never grew up', 46, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('Color with your kids — bring the heroes to life!', 38, False, (110, 110, 110)))

# ── Copyright-page layout ────────────────────────────────────────────────────

COPYRIGHT_PAGE_LINES = (('© 2026 All rights reserved.', 32, True, (40, 40, 40)),
 ('', 18, False, (255, 255, 255)),
 ('No part of this publication may be reproduced', 26, False, (80, 80, 80)),
 ('or distributed without prior written permission.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('All characters are original fictional archetypes', 26, False, (80, 80, 80)),
 ('inspired by the golden age of anime.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('Printed in the United States of America', 26, False, (80, 80, 80)),
 ('First Edition', 26, False, (80, 80, 80)))

# ── Back-matter layout ───────────────────────────────────────────────────────

BACK_PAGE_LINES = (('Thank you for coloring with us!', 55, True, (0, 0, 0)),
 ('', 30, False, (255, 255, 255)),
 ('If you enjoyed this book,', 40, False, (60, 60, 60)),
 ('please leave a review on Amazon.', 40, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('It means the world to us', 34, False, (110, 110, 110)),
 ('and helps other families discover it.', 34, False, (110, 110, 110)))
