"""
books/boo3-test/config.py — Book data manifest

Generated by KDP Dashboard.
Identity, CHARACTERS, and PAGE_SEQUENCE are managed via the dashboard.
Edit TITLE_PAGE_LINES, COPYRIGHT_PAGE_LINES, BACK_PAGE_LINES directly if needed.
"""

import pathlib

# ── Identity ───────────────────────────────────────────────────────────────────

CATEGORY       = "story"
STORY_FORMAT   = "colored"
STORY_LAYOUT   = "top_bottom"
LANGUAGES      = ["fr", "en", "ar"]
TITLE          = "Baba inouva & Joudia"
SUBTITLE       = ""
AUTHOR         = "Marco Belghiti"
INTRO_TEXT     = ""
VALUES_LEARNED = ""

# ── Paths ──────────────────────────────────────────────────────────────────────

IMAGES_DIR = pathlib.Path(__file__).parent.parent.parent / "images" / "boo3-test"
TESTPEN    = ""

# ── Story settings ────────────────────────────────────────────────────────────

STORY_BASE_PROMPT = "Prompt de base pour cette histoire de Baba Inouva et Joudia."

# ── Story Pages ───────────────────────────────────────────────────────────────

PAGES = [
    {
        "page_number":  1,
        "text":         {"fr": "Très haut, là où les montagnes touchent les nuages, vivait une petite fille nommée Joudia. Sa maison était faite de terre chaude et de bois odorant. C’était le plus bel endroit du monde.", "en": "Very high, where the mountains touch the clouds, lived a little girl named Joudia. Her house was made of warm earth and fragrant wood. It was the most beautiful place in the world.", "es": "Muy alto, donde las montañas tocan las nubes, vivía una niña llamada Joudia. Su casa estaba hecha de tierra cálida y madera fragante. Era el lugar más hermoso del mundo.", "ar": "عاليًا جدًا، حيث تلامس الجبال الغيوم، عاشت فتاة صغيرة اسمها جوديا. كان منزلها مصنوعًا من التراب الدافئ والخشب العطر. كان أجمل مكان في العالم."},
        "moral":        "Apprécier la beauté et le calme de l'endroit où l'on vit.",
        "image_prompt": "A sweeping, textured watercolor and gouache illustration for a children's book. A traditional Moroccan adobe village is perched high on a sun-drenched, rugged mountain slope in the Atlas Mountains. The sky is azure blue. The architecture is rustic and warm ocher and terracotta, showing terraced houses. The overall style is soft and inviting."
    },
    {
        "page_number":  2,
        "text":         {"fr": "Joudia n'était pas une petite fille comme les autres. Elle était le cœur de sa maison. Depuis que sa maman était partie au ciel, elle veillait avec amour sur ses deux petits frères.", "en": "Joudia was not a little girl like the others. She was the heart of her home. Since her mother had gone to heaven, she lovingly watched over her two little brothers.", "es": "Joudia no era una niña como las demás. Ella era el corazón de su hogar. Desde que su mamá se había ido al cielo, ella cuidaba con amor a sus dos hermanos pequeños.", "ar": "جوديا لم تكن فتاة صغيرة مثل الأخريات. كانت قلب منزلها. منذ أن ذهبت والدتها إلى السماء، كانت تعتني بمحبة بأخويها الصغيرين."},
        "moral":        "La famille est le trésor le plus précieux que nous possédons.",
        "image_prompt": "A cozy, indoor scene rendered in textured watercolor. Joudia, as defined in the charte graphique (8 years old, rust tunic, dark braided hair), is sitting on a patterned rug, smiling warmly. She is hugging her two younger brothers, who are laughing. Baba Inouva (fixed character: elderly, white beard, brown djellaba) is watching them from the background with a kind smile. Soft, warm light fills the room."
    },
    {
        "page_number":  3,
        "text":         {"fr": "Chaque matin, avant même que le soleil ne se lève derrière les sommets, Joudia ouvrait les yeux. Elle préparait un thé à la menthe qui sentait bon le jardin.", "en": "Every morning, even before the sun rose behind the peaks, Joudia opened her eyes. She prepared a mint tea that smelled good like the garden.", "es": "Cada mañana, incluso antes de que el sol saliera detrás de las cumbres, Joudia abría los ojos. Preparaba un té de menta que olía bien como el jardín.", "ar": "كل صباح، حتى قبل أن تشرق الشمس خلف القمم، كانت جوديا تفتح عينيها. كانت تعد شايًا بالنعناع تفوح منه رائحة طيبة كحديقة."},
        "moral":        "Le courage et la bonté commencent dès le matin.",
        "image_prompt": "A textured watercolor illustration. Joudia (fixed character: braided hair, rust tunic) is visible in a rustic kitchen as the first warm rays of orange and pink light peak over a snowy mountain crest outside the window. She is carefully pouring hot water into a traditional teapot. The room is filled with a soft morning ambiance."
    },
    {
        "page_number":  4,
        "text":         {"fr": "Avec son bâton, Joudia emmenait ses moutons laineux dans la prairie verte. Elle connaissait chaque fleur, chaque caillou et chaque secret du chemin.", "en": "With her stick, Joudia led her woolly sheep into the green meadow. She knew every flower, every pebble, and every secret of the path.", "es": "Con su bastón, Joudia llevaba a sus ovejas lanudas al prado verde. Conocía cada flor, cada guijarro y cada secreto del camino.", "ar": "بعصاها، قادت جوديا أغنامها الصوفية إلى المرعى الأخضر. كانت تعرف كل زهرة، كل حصاة، وكل سر من أسرار الطريق."},
        "moral":        "Respecter et protéger la nature et les animaux.",
        "image_prompt": "A vibrant, textured gouache and watercolor landscape. Joudia (fixed character: braided hair, rust tunic) is leading a small flock of fluffy sheep across a lush green meadow in the mountains. She holds a wooden staff. The background shows rolling terraced fields and distant mountains. The style is soft and poetic."
    },
    {
        "page_number":  5,
        "text":         {"fr": "Dans la forêt, elle ramassait du bois sec pour le feu du soir. C’était un travail difficile pour une petite fille, mais Joudia chantait une douce chanson pour se donner de la force.", "en": "In the forest, she was gathering dry wood for the evening fire. It was a difficult task for a little girl, but Joudia sang a sweet song to give herself strength.", "es": "En el bosque, ella recogía leña seca para el fuego de la tarde. Era un trabajo difícil para una niña pequeña, pero Joudia cantaba una dulce canción para darse fuerza.", "ar": "في الغابة، كانت تجمع الحطب الجاف لنار المساء. كان عملاً صعباً لفتاة صغيرة، لكن جوديا كانت تغني أغنية عذبة لتمنح نفسها القوة."},
        "moral":        "La persévérance transforme une tâche difficile en une victoire.",
        "image_prompt": "A textured gouache and watercolor illustration. Joudia (fixed character: rustic rust tunic, dark braids) is bent over, carefully gathering a large bundle of dry firewood branches in a dense, mossy mountain forest. A few sunbeams filter through the canopy. Her expression is focused and determined. The style has a tactile, paper texture."
    },
    {
        "page_number":  6,
        "text":         {"fr": "Mais attention ! Un secret se cachait dans la forêt sombre. Un monstre de l'ombre, très malin, attendait que la lumière disparaisse pour sortir et tromper les villageois.", "en": "But beware! A secret was hidden in the dark forest. A very cunning shadow monster was waiting for the light to disappear to come out and deceive the villagers.", "es": "¡Pero cuidado! Un secreto se escondía en el bosque oscuro. Un monstruo de la sombra, muy astuto, esperaba que la luz desapareciera para salir y engañar a los aldeanos.", "ar": "ولكن احذروا! كان هناك سر يختبئ في الغابة المظلمة. وحش الظل، شديد المكر، كان ينتظر اختفاء الضوء ليخرج ويخدع القرويين."},
        "moral":        "Apprendre qu'il existe des dangers dont il faut se méfier, mais sans avoir peur.",
        "image_prompt": "A darker, textured watercolor illustration. In a deep, shadowed part of the mountain forest, a cryptic, dark shadow figure is partially concealed behind a massive tree trunk. The shadows of the branches are exaggerated and creepy, appropriate for a child's story. A faint, glowing pair of eyes watches from the dark. The mood is tense but mystical, not overly terrifying."
    },
    {
        "page_number":  7,
        "text":         {"fr": "Baba Inouva, le vieux papa de Joudia, s'inquiétait. Le monstre était malin : il savait imiter les voix des mamans pour que les enfants lui ouvrent la porte !", "en": "Baba Inouva, Joudia's old father, was worried. The monster was cunning: it knew how to imitate mothers' voices so that children would open the door for it!", "es": "Baba Inouva, el viejo padre de Joudia, estaba preocupado. El monstruo era astuto: ¡sabía imitar las voces de las madres para que los niños le abrieran la puerta!", "ar": "كان بابا إينوفا، والد جوديا العجوز، قلقًا. كان الوحش ماكرًا: كان يعرف كيف يقلد أصوات الأمهات ليفتح له الأطفال الباب!"},
        "moral":        "Comprendre l'importance de la communication et des règles de sécurité de ses parents.",
        "image_prompt": "A warm yet worried indoor textured watercolor. Baba Inouva (fixed character: white beard, brown djellaba, taguiya hat) is sitting near a rustic, carved wooden door. He has a pensive, slightly distressed expression, holding a simple lantern that casts soft light. He is speaking to Joudia (fixed character: braided hair), who is listening intently with wide eyes."
    },
    {
        "page_number":  8,
        "text":         {"fr": "Un soir, Baba Inouva appela Joudia. « Ma fille, nous avons besoin d'un secret pour nous reconnaître. Un code que seul nous deux connaissons. »", "en": "One evening, Baba Inouva called Joudia. \"My daughter, we need a secret to recognize each other. A code that only the two of us know.\"", "es": "Una tarde, Baba Inouva llamó a Joudia. \"Hija mía, necesitamos un secreto para reconocernos. Un código que solo nosotras dos conozcamos.\"", "ar": "في إحدى الأمسيات، نادى بابا إينوفا جوديا. \"يا ابنتي، نحتاج إلى سر لنتعرف على بعضنا البعض. رمز لا يعرفه إلا نحن الاثنان.\""},
        "moral":        "La confiance et l'écoute sont les piliers de la famille.",
        "image_prompt": "A cozy, candle-lit textured watercolor illustration. Baba Inouva (fixed character) is holding Joudia's (fixed character) hands. He is whispering into her ear. A specific pair of heavy, detailed silver bracelets are lying on the patterned Moroccan rug beside them, highlighting the upcoming gift."
    },
    {
        "page_number":  9,
        "text":         {"fr": "Il lui offrit de lourds bracelets en argent. « Quand tu frapperas à la porte le soir, fais-les sonner très fort. Ce sera notre chant d'argent. »", "en": "He offered her heavy silver bracelets. \"When you knock on the door in the evening, make them jingle very loudly. That will be our silver song.\"", "es": "Él le ofreció pesadas pulseras de plata. \"Cuando llames a la puerta por la noche, hazlas sonar muy fuerte. Ese será nuestro canto de plata.\"", "ar": "قدم لها أساور فضية ثقيلة. \"عندما تطرقين الباب في المساء، اجعليها ترن بصوت عالٍ جداً. سيكون ذلك أغنيتنا الفضية.\""},
        "moral":        "Apprécier les cadeaux et les traditions familiales.",
        "image_prompt": "A detailed close-up rendered in textured gouache. Baba Inouva (fixed character, hands visible) is gently clasping the detailed, traditional silver bracelets onto Joudia's (fixed character: rustic rust tunic) wrist. The silver is shining under warm light. The intricate details of the traditional engraving are visible."
    },
    {
        "page_number":  10,
        "text":         {"fr": "Joudia s'entraîna. Gling ! Gling ! Gling ! Le son était joyeux et brillant. Baba Inouva sourit : « C'est parfait ! Maintenant, je saurai que c'est toi. »", "en": "Joudia trained. Gling! Gling! Gling! The sound was joyful and bright. Baba Inouva smiled: \"It's perfect! Now I'll know it's you.\"", "es": "Joudia entrenó. ¡Gling! ¡Gling! ¡Gling! El sonido era alegre y brillante. Baba Inouva sonrió: \"¡Es perfecto! Ahora sabré que eres tú.\"", "ar": "تدربت جوديا. جلنج! جلنج! جلنج! كان الصوت مبتهجًا ومشرقًا. ابتسم بابا إينوفا: \"إنه مثالي! الآن سأعرف أنك أنت.\""},
        "moral":        "La joie de se sentir protégé par sa famille.",
        "image_prompt": "A playful, textured watercolor illustration. Joudia (fixed character: braids, rust tunic) is happily and vigorously shaking her wrists, making the silver bracelets tinkle. The sound effect is visualized as glowing, abstract musical notes ‘Gling Gling’ floating around her hands. Baba Inouva (fixed character, background) is laughing warmly."
    },
    {
        "page_number":  11,
        "text":         {"fr": "Un jour, Joudia trouva un endroit rempli de bois sec très, très loin du village. Elle travailla si dur qu'elle ne vit pas le temps passer.", "en": "One day, Joudia found a place full of dry wood very, very far from the village. She worked so hard that she didn't see the time pass.", "es": "Un día, Joudia encontró un lugar lleno de leña muy, muy lejos del pueblo. Trabajó tan duro que no vio pasar el tiempo.", "ar": "في أحد الأيام، وجدت جوديا مكانًا مليئًا بالخشب الجاف بعيدًا جدًا عن القرية. عملت بجد لدرجة أنها لم ترَ الوقت يمر."},
        "moral":        "Parfois, on oublie tout quand on est concentré, mais il faut faire attention au temps.",
        "image_prompt": "A sun-drenched, textured gouache landscape. Joudia (fixed character: rust tunic, braided hair) is deep in a distant part of the mountains, far from the village. She is struggling to carry an oversized, massive bundle of firewood. The sun is now low and bright orange on the horizon, showing she is late."
    },
    {
        "page_number":  12,
        "text":         {"fr": "Le soleil disparut. Soudain, des ombres furtives apparurent. Ce n'était pas un monstre terrifiant, mais des voleurs malicieux qui se faufilèrent hors de la pénombre. Ils effrayèrent Joudia et lui dérobèrent ses beaux bracelets en argent !", "en": "The sun disappeared. Suddenly, stealthy shadows appeared. It wasn't a terrifying monster, but mischievous thieves who snuck out of the gloom. They frightened Joudia and stole her beautiful silver bracelets!", "es": "El sol desapareció. De repente, aparecieron sombras furtivas. No era un monstruo aterrador, sino ladrones traviesos que se escabulleron de la penumbra. Asustaron a Joudia y le robaron sus hermosas pulseras de plata.", "ar": "اختفت الشمس. فجأة، ظهرت ظلال متسللة. لم يكن وحشًا مخيفًا، بل لصوصًا مشاغبين تسللوا من الظلام. أخافوا جوديا وسرقوا أساورها الفضية الجميلة!"},
        "moral":        "Le courage face à une perte matérielle.",
        "image_prompt": "A dramatic, shadowed textured watercolor. Joudia (fixed character) is frightened, running away. Her bare wrists and ankle are noticeably empty. A hazy, shadowy manifestation of the Shadow Monster (fixed character concept) has its hand outstretched, retreating with the shiny silver bracelets and anklet in its grasp. The sky is dark violet."
    },
    {
        "page_number":  13,
        "text":         {"fr": "Sans ses bijoux, Joudia avait peur de ne pas être reconnue. Mais elle pensa à son papa et à ses frères qui l'attendaient. Elle se mit à courir très, très vite vers la maison.", "en": "Without her jewelry, Joudia was afraid she wouldn't be recognized. But she thought of her dad and her brothers who were waiting for her. She started running very, very fast towards the house.", "es": "Sin sus joyas, Joudia tenía miedo de no ser reconocida. Pero pensó en su papá y en sus hermanos que la esperaban. Empezó a correr muy, muy rápido hacia la casa.", "ar": "بدون مجوهراتها، كانت جوديا تخشى ألا يتم التعرف عليها. لكنها فكرت في والدها وإخوتها الذين كانوا ينتظرونها. بدأت تركض بسرعة كبيرة جداً نحو المنزل."},
        "moral":        "La motivation vient de l'amour que l'on porte aux autres.",
        "image_prompt": "A fast-paced, dynamic textured watercolor illustration. Joudia (fixed character: rustic rust tunic, braided hair), now without her silver jewelry, is running urgently down a dark, winding mountain path. She looks determined but scared. The moonlight barely illuminates her way, and the encroaching forest shadows seem to reach for her."
    },
    {
        "page_number":  14,
        "text":         {"fr": "Pendant ce temps, près du village, le monstre malin rôdait autour des maisons. Il imitait de douces voix pour tromper les villageois.", "en": "Meanwhile, near the village, the cunning monster lurked around the houses. It imitated sweet voices to deceive the villagers.", "es": "Mientras tanto, cerca del pueblo, el astuto monstruo merodeaba por las casas. Imitaba voces dulces para engañar a los aldeanos.", "ar": "في هذه الأثناء، بالقرب من القرية، كان الوحش الماكر يتجول حول المنازل. كان يقلد أصواتًا لطيفة لخداع القرويين."},
        "moral":        "Ne pas se fier aux apparences trompeuses.",
        "image_prompt": "A stealthy, dark textured watercolor. The Shadow Monster (fixed character concept: dark, shifting form) is seen hiding behind an adobe house near Baba Inouva's village. It is mimicking a gentle posture and sound, making abstract glowing ripples like an imitation voice. The village looks peaceful and unaware."
    },
    {
        "page_number":  15,
        "text":         {"fr": "Joudia arriva enfin, essoufflée et fatiguée. La porte de sa maison était fermée. Elle frappa de toutes ses forces. « Papa, c'est moi ! Ouvre-moi vite ! La nuit tombe ! » cria-t-elle.", "en": "Joudia finally arrived, out of breath and tired. The door to her house was closed. She knocked with all her might. \"Dad, it's me! Open quickly! Night is falling!\" she cried.", "es": "Joudia finalmente llegó, sin aliento y cansada. La puerta de su casa estaba cerrada. Golpeó con todas sus fuerzas. \"¡Papá, soy yo! ¡Ábreme rápido! ¡Está anocheciendo!\" gritó.", "ar": "وصلت جوديا أخيراً، وهي لاهثة ومتعبة. كان باب منزلها مغلقاً. طرقت بكل قوتها. \"أبي، إنها أنا! افتح لي بسرعة! الليل يهبط!\" صرخت."},
        "moral":        "Persévérer jusqu'au bout, même quand on est fatigué.",
        "image_prompt": "A textured watercolor illustration, matching the emotional tension of image_2.png. Joudia (fixed character: braids, rust tunic, bare wrists and anklet) stands alone and distressed, urgently knocking on the large, weather-carved wooden door of her rustic mud-brick house. The setting is twilight, dark blue-grey shadows are encroaching."
    },
    {
        "page_number":  16,
        "text":         {"fr": "De l’autre côté de la porte, Baba Inouva entendit la voix. C’était la voix de Joudia... mais où était le chant de l’argent ? Il craignait que ce soit un tour du monstre.", "en": "On the other side of the door, Baba Inouva heard the voice. It was Joudia's voice... but where was the sound of money? He feared it was a trick from the monster.", "es": "Al otro lado de la puerta, Baba Inouva escuchó la voz. Era la voz de Joudia... pero ¿dónde estaba el sonido del dinero? Temía que fuera un truco del monstruo.", "ar": "من الجانب الآخر من الباب، سمع بابا إينوفا الصوت. كان صوت جوديا... ولكن أين كان رنين المال؟ لقد خشي أن تكون خدعة من الوحش."},
        "moral":        "Réfléchir avant d'agir pour protéger sa famille.",
        "image_prompt": "A tense indoor textured watercolor, contrasting with image_1.png. Baba Inouva (fixed character: white beard, brown djellaba), now looking extremely worried and cautious, stands alone behind the heavy door, his hand hovering over the lock, listening with a conflicted expression. He is terrified to open it."
    },
    {
        "page_number":  17,
        "text":         {"fr": "« Gling ! Gling ! Gling ! Fais sonner tes bracelets pour me prouver que c'est toi ! » demanda le père d'une voix tremblante. Joudia pleura : « Je ne peux pas, papa ! On me les a volés ! »", "en": "Cling! Cling! Cling! Make your bracelets jingle to prove it's you!\" the father asked with a trembling voice. Joudia cried, \"I can't, Papa! They were stolen from me!\"", "es": "¡Gling! ¡Gling! ¡Gling! ¡Haz sonar tus pulseras para probarme que eres tú!\" preguntó el padre con voz temblorosa. Joudia lloró: \"¡No puedo, papá! ¡Me las robaron!\"", "ar": "جلينغ! جلينغ! جلينغ! اجعلي أساورك ترن لتثبتي لي أنك أنتِ!\" سأل الأب بصوت مرتجف. بكت جوديا: \"لا أستطيع يا أبي! لقد سرقت مني!\""},
        "moral":        "Savoir admettre quand on a perdu quelque chose d'important.",
        "image_prompt": "A detailed close-up, rendered in textured gouache. On the inside of the carved wooden door, Baba Inouva (fixed character) is distressed. On the outside, Joudia's (fixed character) face is shown looking up at the door crack, tears welling up. Her bare wrists are pressed against the rough wood, emphasizing the missing code."
    },
    {
        "page_number":  18,
        "text":         {"fr": "Baba Inouva était perdu. Il ne connaissait sa fille que par son travail difficile et le bruit de ses bijoux. S'il n'ouvrait pas, sa fille resterait dehors dans le froid. S'il ouvrait au monstre, ses enfants seraient en danger.", "en": "Baba Inouva was lost. He only knew his daughter by her hard work and the sound of her jewelry. If he didn't open, his daughter would remain outside in the cold. If he opened to the monster, his children would be in danger.", "es": "Baba Inouva estaba perdido. Solo conocía a su hija por su arduo trabajo y el sonido de sus joyas. Si no abría, su hija se quedaría afuera en el frío. Si le abría al monstruo, sus hijos estarían en peligro.", "ar": "كان بابا إينوفا تائهاً. لم يكن يعرف ابنته إلا من خلال عملها الشاق وصوت مجوهراتها. إذا لم يفتح الباب، فستبقى ابنته في الخارج في البرد. وإذا فتح للوحش، فسيكون أطفاله في خطر."},
        "moral":        "Faire des choix difficiles demande de la sagesse et du cœur.",
        "image_prompt": "A heartwarming but anxious indoor textured watercolor. Inside the cozy adobe home, Baba Inouva (fixed character: brown djellaba, white beard) sits with his head in his hands, conflicted. His two little brothers (image_0.png reference: small boys) are sleeping peacefully on mats in the background shadows, oblivious. The single lantern throws flickering light."
    },
    {
        "page_number":  19,
        "text":         {"fr": "Soudain, dans son désespoir, Baba Inouva comprit quelque chose d'important. Les bracelets n'étaient que du métal. Il chercha dans son cœur quelque chose de vrai que seul lui et Joudia savaient.", "en": "Suddenly, in his despair, Baba Inouva understood something important. The bracelets were just metal. He searched in his heart for something true that only he and Joudia knew.", "es": "De repente, en su desesperación, Baba Inouva comprendió algo importante. Las pulseras eran solo metal. Buscó en su corazón algo verdadero que solo él y Joudia sabían.", "ar": "فجأة، في يأسِه، فهم بابا إينوفا شيئًا مهمًا. لم تكن الأساور سوى معدن. بحث في قلبه عن شيء حقيقي لا يعرفه إلا هو وجوديا."},
        "moral":        "Ce que l'on ne voit pas (l'amour, les secrets) est plus fort que ce que l'on voit.",
        "image_prompt": "A poetic, textured gouache illustration. Inside the house, Baba Inouva (fixed character) is kneeling against the wooden door. Soft, warm light seems to radiate from his chest, highlighting his kind face. He is no longer confused, but focused. The style is gentle and intimate."
    },
    {
        "page_number":  20,
        "text":         {"fr": "Il s'approcha de la porte et murmura : « Dis-moi, ma fille... quel est le petit nom doux que je te donne quand je te borde le soir et que nous regardons les étoiles ? »", "en": "He approached the door and whispered, \"Tell me, my daughter... what is the sweet little name I call you when I tuck you in at night and we look at the stars?\"", "es": "Se acercó a la puerta y susurró: \"Dime, hija mía... ¿cuál es el dulce nombrecito que te doy cuando te arropo por la noche y miramos las estrellas?\"", "ar": "اقترب من الباب وهمس: \"قولي لي يا ابنتي... ما هو الاسم الصغير اللطيف الذي أناديك به عندما أغطيك في المساء ونحن ننظر إلى النجوم؟\""},
        "moral":        "L'intimité et les doux souvenirs partagés sont le vrai secret d'une famille.",
        "image_prompt": "A magical-feeling textured watercolor. Outside, the night sky is now deep blue and filled with bright stars. Joudia (fixed character: rust tunic, braided hair) stops crying. Her expression transforms into quiet recognition. Soft, ethereal light bridges the distance between her and the door crack."
    },
    {
        "page_number":  21,
        "text":         {"fr": "Joudia se souvint. Elle murmura doucement à travers la porte : « Tu m'appelles 'Ma petite fleur des montagnes', papa. Car tu dis que je suis forte comme une fleur qui pousse entre deux pierres. »", "en": "Joudia remembered. She whispered softly through the door: \"You call me 'My little mountain flower', Papa. Because you say I am strong like a flower that grows between two stones.\"", "es": "Joudia recordó. Susurró suavemente a través de la puerta: \"Me llamas 'Mi pequeña flor de la montaña', papá. Porque dices que soy fuerte como una flor que crece entre dos piedras.\"", "ar": "تذكرت جوديا. همست بهدوء عبر الباب: \"أنت تناديني 'زهرتي الجبلية الصغيرة'، يا أبي. لأنك تقول إنني قوية كزهرة تنمو بين حجرين.\""},
        "moral":        "Se souvenir des mots d'amour de ses parents nous donne de la force.",
        "image_prompt": "A heartwarming textured gouache illustration. Outside, Joudia (fixed character) smiles through her tears. A visualization of a delicate, glowing orange mountain flower appears near her lips, representing her words. The visualization matches the emotional shift toward safety and love."
    },
    {
        "page_number":  22,
        "text":         {"fr": "Le verrou grinça et la grande porte en bois s'ouvrit ! Une lumière chaude enveloppa Joudia. Elle était enfin à l'abri. « C’est bien toi, ma fleur ! » cria Baba Inouva.", "en": "The bolt creaked and the large wooden door opened! A warm light enveloped Joudia. She was finally safe. \"It's really you, my flower!\" cried Baba Inouva.", "es": "¡El cerrojo chirrió y la gran puerta de madera se abrió! Una luz cálida envolvió a Joudia. Por fin estaba a salvo. \"¡Eres tú, mi flor!\" gritó Baba Inouva.", "ar": "صرير المزلاج وانفتحت البوابة الخشبية الكبيرة! غمر ضوء دافئ جوديا. كانت آمنة أخيرًا. \"إنها أنتِ حقًا، يا زهرتي!\" صرخ بابا إينوفا."},
        "moral":        "Le soulagement et la joie de se retrouver après l'épreuve.",
        "image_prompt": "A joyous, textured watercolor and gouache illustration, referencing the style of image_3.png. The rustic carved wooden door of the adobe house (as seen in image_0.png and image_2.png) is fully open, spilling warm, golden light onto the dark street. Baba Inouva (fixed character: white beard) is kneeling, hugging Joudia (fixed character: rustic tunic, braids) very tightly. Her expression is pure relief and joy."
    },
    {
        "page_number":  23,
        "text":         {"fr": "Ce soir-là, toute la famille se réunit autour du feu. Baba Inouva serra la main de Joudia. Il comprit que son lien avec sa fille était bien plus profond que de simples bijoux ou le travail qu'elle faisait. C'était un lien d'amour véritable.", "en": "That evening, the whole family gathered around the fire. Baba Inouva squeezed Joudia's hand. He understood that his bond with his daughter was much deeper than mere jewelry or the work she did. It was a bond of true love.", "es": "Esa noche, toda la familia se reunió alrededor del fuego. Baba Inouva apretó la mano de Joudia. Comprendió que su vínculo con su hija era mucho más profundo que simples joyas o el trabajo que ella hacía. Era un vínculo de amor verdadero.", "ar": "في تلك الليلة، اجتمعت العائلة بأكملها حول النار. ضغط بابا إينوفا على يد جوديا. أدرك أن علاقته بابنته كانت أعمق بكثير من مجرد مجوهرات أو العمل الذي كانت تقوم به. كانت علاقة حب حقيقية."},
        "moral":        "L'amour inconditionnel est la plus grande des protections.",
        "image_prompt": "A tender, cozy indoor scene in textured watercolor. The whole family (Baba Inouva, Joudia with rustic tunic and braided hair, and the two young brothers from image_0.png) is gathered closely around a warming earthen firepit. Baba Inouva is holding Joudia's hand tenderly. They are drinking tea, smiling. The light is soft and glowing."
    },
    {
        "page_number":  24,
        "text":         {"fr": "Joudia s'endormit en sachant que le plus beau des bracelets ne valait pas un mot d'amour de son papa. Et le monstre de l’ombre, voyant tant d’amour, s'en alla loin, très loin de ce village courageux.", "en": "Joudia fell asleep knowing that the most beautiful bracelet was not worth a word of love from her dad. And the shadow monster, seeing so much love, went far, far away from this courageous village.", "es": "Joudia se durmió sabiendo que la pulsera más hermosa no valía una palabra de amor de su papá. Y el monstruo de la sombra, viendo tanto amor, se fue lejos, muy lejos de este valiente pueblo.", "ar": "نامت جوديا وهي تعلم أن أجمل الأساور لا تساوي كلمة حب من والدها. والوحش الظلي، عندما رأى كل هذا الحب، ذهب بعيدًا، بعيدًا جدًا عن هذه القرية الشجاعة."},
        "moral":        "",
        "image_prompt": "A peaceful, textured watercolor illustration. A exterior shot of the quiet mountain village under a beautiful star-filled night sky, referencing image_0.png's architecture. Silence reigns. Inside one window, we see a close-up of Joudia (fixed character) sleeping soundly on her mat, a slight smile on her face. Her hand is tucked under her head. A subtle glow of warmth emanates from the house. A safe, secure conclusion."
    }
]

# ── Character roster ──────────────────────────────────────────────────────────

CHARACTERS = []

# ── Page sequence ─────────────────────────────────────────────────────────────

PAGE_SEQUENCE = [
    ("boo3-test_page_1.png", "Page 1"),
    ("boo3-test_page_2.png", "Page 2"),
    ("boo3-test_page_3.png", "Page 3"),
    ("boo3-test_page_4.png", "Page 4"),
    ("boo3-test_page_5.png", "Page 5"),
    ("boo3-test_page_6.png", "Page 6"),
    ("boo3-test_page_7.png", "Page 7"),
    ("boo3-test_page_8.png", "Page 8"),
    ("boo3-test_page_9.png", "Page 9"),
    ("boo3-test_page_10.png", "Page 10"),
    ("boo3-test_page_11.png", "Page 11"),
    ("boo3-test_page_12.png", "Page 12"),
    ("boo3-test_page_13.png", "Page 13"),
    ("boo3-test_page_14.png", "Page 14"),
    ("boo3-test_page_15.png", "Page 15"),
    ("boo3-test_page_16.png", "Page 16"),
    ("boo3-test_page_17.png", "Page 17"),
    ("boo3-test_page_18.png", "Page 18"),
    ("boo3-test_page_19.png", "Page 19"),
    ("boo3-test_page_20.png", "Page 20"),
    ("boo3-test_page_21.png", "Page 21"),
    ("boo3-test_page_22.png", "Page 22"),
    ("boo3-test_page_23.png", "Page 23"),
    ("boo3-test_page_24.png", "Page 24")
]

# ── KDP Metadata ────────────────────────────────────────────────────────────────

KDP_METADATA = {}

# ── Title-page layout ─────────────────────────────────────────────────────────

TITLE_PAGE_LINES = (('baba inva', 120, True, (0, 0, 0)),
 ('Coloring Our Stories', 72, True, (0, 0, 0)),
 ('', 36, False, (255, 255, 255)),
 ('', 46, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('Color with your kids — bring the heroes to life!', 38, False, (110, 110, 110)))

# ── Copyright-page layout ────────────────────────────────────────────────────

COPYRIGHT_PAGE_LINES = (('© 2026 All rights reserved.', 32, True, (40, 40, 40)),
 ('', 18, False, (255, 255, 255)),
 ('No part of this publication may be reproduced', 26, False, (80, 80, 80)),
 ('or distributed without prior written permission.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('All characters are original fictional archetypes', 26, False, (80, 80, 80)),
 ('inspired by the world of anime.', 26, False, (80, 80, 80)),
 ('', 18, False, (255, 255, 255)),
 ('Printed in the United States of America', 26, False, (80, 80, 80)),
 ('First Edition', 26, False, (80, 80, 80)))

# ── Back-matter layout ───────────────────────────────────────────────────────

BACK_PAGE_LINES = (('Thank you for coloring with us!', 55, True, (0, 0, 0)),
 ('', 30, False, (255, 255, 255)),
 ('If you enjoyed this book,', 40, False, (60, 60, 60)),
 ('please leave a review on Amazon.', 40, False, (60, 60, 60)),
 ('', 24, False, (255, 255, 255)),
 ('It means the world to us', 34, False, (110, 110, 110)),
 ('and helps other families discover it.', 34, False, (110, 110, 110)))
